# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

# Run this workflow every time you push to the `main` branch
on:
  push:
    branches: ['main'] # Change to your default branch name if it's not `main`

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a recent LTS version
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build the project
        # This command must match your build script in package.json
        working-directory: ./frontend 
        run: npm run build 

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload the build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should be the folder your build command generates
          path: './frontend/dist' 
         

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4